ARG TRIVY_VERSION
ARG TRIVY_API_VERSION

# Build stage
FROM golang:1.19.2-alpine3.16 AS buildTriviApi
ENV COOS linux
ADD ./api/ /go/src
ADD ./src/api /go/src
WORKDIR /go/src
RUN go build -o scanner-trivy cmd/scanner-trivy/main.go


# Final stage
FROM aquasec/trivy:${TRIVY_VERSION}
ARG TRIVY_VERSION
ARG TRIVY_API_VERSION
RUN adduser -u 10000 -D -g '' scanner scanner

COPY --from=buildTriviApi /go/src/scanner-trivy /home/scanner/bin/scanner-trivy

ENV TRIVY_VERSION=${TRIVY_VERSION}
ENV TRIVY_API_VERSION=${TRIVY_API_VERSION}

USER scanner
ENTRYPOINT ["/home/scanner/bin/scanner-trivy"]