# Build stage
FROM golang:1.19.2-alpine3.16 as builder

ARG DB_TYPE=trivy

WORKDIR /build
COPY ./db /build
SHELL ["/bin/sh", "-o", "pipefail", "-c"]

RUN apk --no-cache add make gzip

RUN DB_TYPE=${DB_TYPE} make db-all

# Final stage
FROM scratch
COPY --from=builder /build/assets/db.tar.gz .